env:
  browser: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  no-plusplus: 'error',
  no-unused-vars: 'off',
  semi: ['error', 'always'],
  '@typescript-eslint/no-empty-function': 'off',
  no-useless-return: 'off',
}
